export const employeeData: Object[] = [
  {
    EmployeeID: 10001,
    Employees: 'Kathryn Fuller',
    EmployeeImg: 'userfemale',
    Designation: 'Designer',
    Mail: 'kathryn98@example.com',
    Location: 'Mexico',
    Status: 'Active',
    Trustworthiness: 'Sufficient',
    Rating: 3,
    Software: 62,
    CurrentSalary: 45000,
    Address: '507 - 20th Ave. E. Apt. 2A'
  },
  {
    EmployeeID: 10002,
    Employees: 'Tamer Fuller',
    EmployeeImg: 'usermale',
    Designation: 'Manager',
    Mail: 'tamer10@example.com',
    Location: 'Canada',
    Status: 'Inactive',
    Trustworthiness: 'Perfect',
    Rating: 4,
    Software: 78,
    CurrentSalary: 68000,
    Address: '908 W. Capital Way'
  },
  {
    EmployeeID: 10003,
    Employees: 'Martin Nancy',
    EmployeeImg: 'usermale',
    Designation: 'Project Lead',
    Mail: 'martin58@example.com',
    Location: 'USA',
    Status: 'Inactive',
    Trustworthiness: 'Insufficient',
    Rating: 2,
    Software: 44,
    CurrentSalary: 52000,
    Address: '722 Moss Bay Blvd.'
  },
  {
    EmployeeID: 10004,
    Employees: 'Davolio Leverling',
    EmployeeImg: 'usermale',
    Designation: 'Developer',
    Mail: 'davolio31@example.com',
    Location: 'Austria',
    Status: 'Active',
    Trustworthiness: 'Perfect',
    Rating: 5,
    Software: 90,
    CurrentSalary: 72000,
    Address: '4110 Old Redmond Rd.'
  },
  {
    EmployeeID: 10005,
    Employees: 'Nancy Fuller',
    EmployeeImg: 'userfemale',
    Designation: 'System Analyst',
    Mail: 'nancy87@example.com',
    Location: 'Argentina',
    Status: 'Inactive',
    Trustworthiness: 'Perfect',
    Rating: 4,
    Software: 55,
    CurrentSalary: 61000,
    Address: '14 Garrett Hill'
  },
  {
    EmployeeID: 10006,
    Employees: 'Fuller Margaret',
    EmployeeImg: 'userfemale',
    Designation: 'CFO',
    Mail: 'fuller23@example.com',
    Location: 'Sweden',
    Status: 'Active',
    Trustworthiness: 'Sufficient',
    Rating: 3,
    Software: 70,
    CurrentSalary: 95000,
    Address: 'Coventry House Miner Rd.'
  },
  {
    EmployeeID: 10007,
    Employees: 'Leverling Andrew',
    EmployeeImg: 'usermale',
    Designation: 'CFO',
    Mail: 'leverling49@example.com',
    Location: 'Germany',
    Status: 'Active',
    Trustworthiness: 'Insufficient',
    Rating: 3,
    Software: 48,
    CurrentSalary: 88000,
    Address: 'Edgeham Hollow Winchester Way'
  },
  {
    EmployeeID: 10008,
    Employees: 'Peacock Buchanan',
    EmployeeImg: 'usermale',
    Designation: 'Program Director',
    Mail: 'peacock62@example.com',
    Location: 'Austria',
    Status: 'Active',
    Trustworthiness: 'Perfect',
    Rating: 4,
    Software: 82,
    CurrentSalary: 76000,
    Address: '4726 - 11th Ave. N.E.'
  },
  {
    EmployeeID: 10009,
    Employees: 'Margaret Buchanan',
    EmployeeImg: 'userfemale',
    Designation: 'Manager',
    Mail: 'margaret18@example.com',
    Location: 'France',
    Status: 'Inactive',
    Trustworthiness: 'Insufficient',
    Rating: 2,
    Software: 35,
    CurrentSalary: 58000,
    Address: '7 Houndstooth Rd.'
  },
  {
    EmployeeID: 10010,
    Employees: 'Buchanan Laura',
    EmployeeImg: 'userfemale',
    Designation: 'Developer',
    Mail: 'buchanan7@example.com',
    Location: 'UK',
    Status: 'Inactive',
    Trustworthiness: 'Insufficient',
    Rating: 2,
    Software: 40,
    CurrentSalary: 49000,
    Address: 'Rua Flos de Mayo'
  }
];
